# Generated by Django 2.1.1 on 2018-10-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_user_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
