# Generated by Django 2.1.1 on 2018-10-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_emailverifyrecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.ImageField(blank=True, max_length=420, upload_to=''),
        ),
    ]
