# Generated by Django 2.1.1 on 2018-09-19 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20180918_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
