# Generated by Django 2.1.1 on 2018-10-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20180930_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
