# Generated by Django 2.1.1 on 2018-10-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/static/imgs/default_photo.jpg', upload_to='profile_image'),
        ),
    ]
