# Generated by Django 2.1.1 on 2018-10-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_auto_20181001_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=64)),
            ],
        ),
    ]
