# Generated by Django 2.1.1 on 2018-10-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0007_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
