# Generated by Django 2.1.1 on 2018-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
