# Generated by Django 2.1.1 on 2018-10-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
