# Generated by Django 2.1.1 on 2018-09-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='time_str',
        ),
    ]
